language: node_js
node_js: stable
install:
- npm install
script:
- hexo cl
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "wangxiang"
- git config user.email "wangxiang@yixia.com"
- git add .
- git commit -m "update"
- git push --force --quiet "https://${f629858390741037d1ef306dd32b8d8129301d55}@${github.com/shinewang1991/shinewang1991.github.io.git}"
  master:master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/shinewang1991/shinewang1991.github.io.git
before_install:

  # 解密私钥
- openssl aes-256-cbc -K $encrypted_d5ccff8f34ef_key -iv $encrypted_d5ccff8f34ef_iv
  -in vps_rsa.enc -out vps_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "wangxiang"
- git config --global user.email wangxiang@yixia.com

