language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成
  # - hexo d  #发布    自己在这里坑了很久，因为用了下面的after_script会自动push静态资源文件到仓库里，就是就是代替了hexo d命令。 

after_script:
  - cd ./public
  - git init
  - git config user.name "wangxiang"  #修改name
  - git config user.email "wangxiang@yixia.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${f629858390741037d1ef306dd32b8d8129301d55}@${github.com/shinewang1991/shinewang1991.github.io.git}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/shinewang1991/shinewang1991.github.io.git  #设置GH_REF，注意更改yourname